//! Audio clip stage: renders audio clip instances frame by frame into their track's channel
//! while advancing a local tick cursor that follows the tempo map and the loop region.
//!
//! Reads: clips (PCM), project settings (tempo, PPQ), the device sample rate and the per-frame
//! tick rates. Writes: tracks (each instance's `playback_position`) and channels (`buffer_left`
//! and `buffer_right`, added to).

use std::collections::HashMap;

use super::timeline::{advance_tick, frame_rate_at};
use crate::audio::channel::Channel;
use crate::audio::clip::{AudioPlayback, Clip, ClipInstance, ClipType};
use crate::audio::dsp::gain::db_to_gain;
use crate::audio::project::ProjectSettings;
use crate::audio::track::Track;
use crate::audio::types::*;

/// Where in the timeline a buffer starts and how long it is, for the audio clip render.
#[derive(Clone, Copy)]
pub(super) struct BufferSpan {
    /// Playhead tick at the start of the buffer.
    pub start_tick: Tick,
    /// Fractional tick accumulator at the start of the buffer.
    pub start_acc: f64,
    /// Frames in the buffer.
    pub frames: usize,
    /// Loop region `[start, end)` in ticks, if looping.
    pub loop_region: Option<(Tick, Tick)>,
    /// Real device sample rate.
    pub sample_rate: f32,
}

/// Generate audio clip content per frame into each track's channel.
///
/// The local tick cursor advances with `tick_rates` exactly like the tick-event stage, so both
/// agree on where the loop wraps. A loop wrap re-seats every audio instance.
pub(super) fn render_audio_clips(
    tracks: &mut HashMap<TrackId, Track>,
    clips: &HashMap<ClipId, Clip>,
    channels: &mut HashMap<ChannelId, Channel>,
    settings: &ProjectSettings,
    device_sample_rate: f32,
    tick_rates: &[f64],
    span: BufferSpan,
) {
    let mut render_tick = span.start_tick;
    let mut render_acc = span.start_acc;
    for frame_idx in 0..span.frames {
        // Advance local tick based on ticks_per_sample
        let frame_rate = frame_rate_at(tick_rates, frame_idx);
        render_acc += frame_rate;
        if render_acc >= 1.0 {
            let inc = render_acc.floor() as Tick;
            let (next, wrapped) = advance_tick(render_tick, inc, span.loop_region);
            render_tick = next;
            render_acc -= inc as f64;
            if wrapped {
                // Audio clips re-seat at the loop start like after a seek
                for track in tracks.values_mut() {
                    for instance in &mut track.clip_instances {
                        instance.playback_position = None;
                    }
                }
            }
        }

        let current_tick = render_tick;
        let frame_bpm = frame_rate * 60.0 * span.sample_rate as f64 / settings.ppq as f64;

        // Generate audio from each track
        for track in tracks.values_mut() {
            let mut sample_left = 0.0;
            let mut sample_right = 0.0;

            // Note: MIDI audio is now generated by the channel's instrument device (if present)
            // Tracks no longer hold active voices - they only route MIDI to channels

            // Process audio clips on this track
            for instance in track.clip_instances.iter_mut() {
                if instance.muted {
                    continue;
                }

                if let Some(clip) = clips.get(&instance.clip_id) {
                    if clip.clip_type == ClipType::Audio && !clip.audio_samples.is_empty() {
                        mix_instance_frame(
                            instance,
                            clip,
                            settings,
                            device_sample_rate,
                            current_tick,
                            frame_bpm,
                            &mut sample_left,
                            &mut sample_right,
                        );
                    }
                }
            }

            // Write to track's channel
            if let Some(channel) = channels.get_mut(&track.channel_id) {
                if frame_idx < channel.buffer_left.len() {
                    channel.buffer_left[frame_idx] += sample_left;
                    channel.buffer_right[frame_idx] += sample_right;
                }
            }
        }
    }
}

/// Add one frame of an audio clip instance to the track's running `sample_left`/`sample_right`
/// and advance the instance's playback position (looping it if enabled).
///
/// An instance outside its playback range at `current_tick` drops its position instead.
fn mix_instance_frame(
    instance: &mut ClipInstance,
    clip: &Clip,
    settings: &ProjectSettings,
    device_sample_rate: f32,
    current_tick: Tick,
    frame_bpm: f64,
    sample_left: &mut f32,
    sample_right: &mut f32,
) {
    let current_pos_in_instance = current_tick - instance.start_tick;
    // A clip without a recorded BPM plays 1:1 at the project tempo
    let recorded_bpm = if clip.recorded_bpm > 0.0 {
        clip.recorded_bpm
    } else {
        settings.tempo
    };

    // Check if we're in the playback range for this instance
    if current_pos_in_instance >= 0 && current_pos_in_instance < instance.duration_ticks {
        // Initialize playback position for this clip instance if not yet started
        // Apply clip_offset: start reading from the offset position in the clip
        // PLUS account for seeking into the middle of the instance
        if instance.playback_position.is_none() {
            // Total offset = clip_offset (trim) + current position in instance (seek)
            let total_offset_ticks =
                instance.wrap_content_tick(instance.clip_offset + current_pos_in_instance);

            // Convert total offset (ticks) to sample index in the clip's sample-rate domain
            instance.playback_position = Some(AudioPlayback::clip_source_frame(
                total_offset_ticks,
                recorded_bpm,
                settings.ppq,
                clip.audio_sample_rate as f64,
            ));
        }

        // Get mutable reference to playback position
        let Some(playback_pos) = instance.playback_position.as_mut() else {
            return;
        };

        // Source frames to advance this frame at the tempo playing now
        let advance_per_sample = AudioPlayback::clip_advance_per_frame(
            frame_bpm,
            recorded_bpm,
            clip.audio_sample_rate as f64,
            device_sample_rate as f64,
        );

        let clip_sample_len = (clip.audio_samples.len() / clip.audio_channels) as f64;

        // A reversed instance reads the source mirrored around its centre,
        // while the playback position (and any loop wrap) still advances
        // forward in content time.
        let read_pos = if instance.reverse {
            AudioPlayback::reverse_source_frame(*playback_pos, clip_sample_len)
        } else {
            *playback_pos
        };

        // Get the current interpolated sample
        let sample_idx = read_pos.floor() as usize;
        let frac = (read_pos.fract()) as f32;

        if sample_idx < clip_sample_len as usize {
            let interleaved_idx = sample_idx * clip.audio_channels;
            let next_idx = sample_idx + 1;
            let interleaved_idx_next = if next_idx < clip_sample_len as usize {
                next_idx * clip.audio_channels
            } else {
                interleaved_idx
            };

            // Linear interpolation for left channel
            if interleaved_idx < clip.audio_samples.len() {
                let s0_left = clip.audio_samples[interleaved_idx];
                let s1_left = if interleaved_idx_next < clip.audio_samples.len()
                    && interleaved_idx_next != interleaved_idx
                {
                    clip.audio_samples[interleaved_idx_next]
                } else {
                    s0_left
                };
                *sample_left += s0_left + frac * (s1_left - s0_left);
            }

            // Linear interpolation for right channel
            if clip.audio_channels > 1 && interleaved_idx + 1 < clip.audio_samples.len() {
                let s0_right = clip.audio_samples[interleaved_idx + 1];
                let s1_right = if interleaved_idx_next + 1 < clip.audio_samples.len()
                    && interleaved_idx_next != interleaved_idx
                {
                    clip.audio_samples[interleaved_idx_next + 1]
                } else {
                    s0_right
                };
                *sample_right += s0_right + frac * (s1_right - s0_right);
            } else if clip.audio_channels == 1 {
                // Mono: duplicate the interpolated left sample for right
                *sample_right += *sample_left;
            }

            // Apply gain offset
            let gain_linear = db_to_gain(instance.gain_offset);
            *sample_left *= gain_linear;
            *sample_right *= gain_linear;
        }

        // Advance playback position for next frame
        *playback_pos += advance_per_sample;

        // Handle looping
        if instance.loop_enabled && instance.loop_length_ticks > 0 {
            let clip_sr = clip.audio_sample_rate as f64;
            let ppq = settings.ppq;
            let loop_start_samples = AudioPlayback::clip_source_frame(
                instance.loop_start_ticks,
                recorded_bpm,
                ppq,
                clip_sr,
            );
            let loop_length_samples = AudioPlayback::clip_source_frame(
                instance.loop_length_ticks,
                recorded_bpm,
                ppq,
                clip_sr,
            );

            if loop_length_samples > 0.0
                && *playback_pos >= loop_start_samples + loop_length_samples
            {
                let offset_in_loop = *playback_pos - loop_start_samples;
                *playback_pos = loop_start_samples + (offset_in_loop % loop_length_samples);
            }
        }
    } else if current_pos_in_instance < 0 {
        // Not yet at clip start, ensure position is reset
        instance.playback_position = None;
    } else {
        // Past clip end, remove position tracking
        instance.playback_position = None;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::audio::processing::process_audio;
    use crate::audio::state::EngineState;
    use std::time::Instant;

    #[test]
    fn clip_seek_is_tempo_independent() {
        // 960 ticks into a clip recorded at 120 BPM, whatever the project tempo
        for _project_bpm in [60.0, 120.0, 200.0] {
            assert_eq!(
                AudioPlayback::clip_source_frame(960, 120.0, 960, 48_000.0),
                24_000.0
            );
        }
    }

    #[test]
    fn reverse_reads_the_file_backwards() {
        // Position 0 is the last frame; the end clamps to the first frame.
        assert_eq!(AudioPlayback::reverse_source_frame(0.0, 1_000.0), 999.0);
        assert_eq!(AudioPlayback::reverse_source_frame(999.0, 1_000.0), 0.0);
        assert_eq!(AudioPlayback::reverse_source_frame(1_000.0, 1_000.0), 0.0);
    }

    /// One 64-frame buffer of a mono ramp clip on track 2, played at 1:1 (120 BPM, 48 kHz).
    fn render_ramp(reverse: bool) -> Vec<f32> {
        let mut state = EngineState::default();

        let mut clip = Clip::new("c".to_string(), "Ramp".to_string(), ClipType::Audio);
        clip.audio_samples = (0..200).map(|i| i as f32).collect();
        clip.audio_channels = 1;
        clip.audio_sample_rate = 48_000;
        clip.recorded_bpm = 120.0;
        clip.content_length_ticks = 960;
        state.clips.insert("c".to_string(), clip);

        let mut instance = ClipInstance::new("i".to_string(), "c".to_string(), 0, 960);
        instance.reverse = reverse;
        let mut track = Track::new(2, 2);
        track.clip_instances.push(instance);
        state.tracks.insert(2, track);
        state
            .channels
            .insert(2, Channel::new(2, "Audio".to_string(), 64, 48_000.0));

        state.set_is_playing(true);
        state.set_current_tick(0);
        state.set_fractional_tick_accumulator(0.0);
        process_audio(&mut state, 64, 48_000.0, Instant::now());
        state.channels.get(&2).unwrap().buffer_left.clone()
    }

    #[test]
    fn reverse_instance_plays_the_clip_backwards() {
        let forward = render_ramp(false);
        let backward = render_ramp(true);
        // 1:1 playback, so frame i reads source frame i forwards and 199 - i reversed.
        assert_eq!(forward[0], 0.0);
        assert_eq!(forward[63], 63.0);
        assert_eq!(backward[0], 199.0);
        assert_eq!(backward[63], 136.0);
    }

    #[test]
    fn clip_loop_bounds_on_clip_timeline() {
        // A one-beat loop of a 120 BPM clip wraps at 24 000 frames at 60 and 200 BPM alike
        let loop_len = AudioPlayback::clip_source_frame(960, 120.0, 960, 48_000.0);
        assert_eq!(loop_len, 24_000.0);
    }

    #[test]
    fn clip_rate_follows_tempo() {
        assert_eq!(
            AudioPlayback::clip_advance_per_frame(120.0, 120.0, 48_000.0, 48_000.0),
            1.0
        );
        assert_eq!(
            AudioPlayback::clip_advance_per_frame(60.0, 120.0, 48_000.0, 48_000.0),
            0.5
        );
        assert!(
            (AudioPlayback::clip_advance_per_frame(200.0, 120.0, 48_000.0, 48_000.0) - 5.0 / 3.0)
                .abs()
                < 1e-12
        );
    }
}
