## SimpleLayoutGenerator.gd
## Builds a Simple View layout from a device's parameters: device kind → classify → compounds →
## groups → pages (docs/specs/004-simple-view/design.md). Every step works on plain data.

class_name SimpleLayoutGenerator extends RefCounted

const MAIN_PAGE_TITLE := "Main"
## Version of the generation rules. Saved in each layout; a layout the user never edited that
## was generated by an older version is generated again when it's loaded.
const VERSION := 4


## Strategy for a `DeviceKind` value.
static func strategy_for(kind: String) -> GenericStrategy:
	match kind:
		DeviceKind.SYNTH:
			return SynthStrategy.new()
		DeviceKind.REVERB:
			return ReverbStrategy.new()
		DeviceKind.DELAY:
			return DelayStrategy.new()
		DeviceKind.COMPRESSOR:
			return CompressorStrategy.new()
		DeviceKind.EQ:
			return EqStrategy.new()
		_:
			return GenericStrategy.new()


## Generate a layout for `device` from `params` (an instance's parameters; falls back to the
## device's own list when empty).
static func generate(device: Device, params: Array, rows: int = SimpleLayout.DEFAULT_ROWS) -> SimpleLayout:
	if params.is_empty() and device != null:
		params = device.parameters
	var kind := DeviceKind.infer(device)
	var strategy := strategy_for(kind)
	var items := CompoundDetector.detect(ParamClassifier.classify(params, strategy))

	var layout := SimpleLayout.new()
	layout.device_id = device.device_id if device != null else ""
	layout.kind = kind
	layout.generated = true
	layout.generator_version = VERSION
	layout.rows = maxi(1, rows)
	layout.pages = build_pages(items, strategy, layout.rows)
	return layout


## Pages for `items` (REQ-007, REQ-008): a Main page with every group the strategy doesn't send to
## a page of its own, then those pages. Pages grow sideways up to `SimpleLayout.MAX_PAGE_COLUMNS`.
static func build_pages(items: Array[Dictionary], strategy: GenericStrategy, rows: int) -> Array[Dictionary]:
	var main: Array[Dictionary] = []
	var others: Array[Dictionary] = []
	for group in group_items(items, strategy):
		group.page = page_for_group(group, strategy)
		if group.page.is_empty():
			group.page = MAIN_PAGE_TITLE
			main.append(group)
		else:
			others.append(group)
	return GridPacker.pack_pages(main + others, rows, SimpleLayout.MAX_PAGE_COLUMNS)


## Page title for `group`, or "" for Main: the page most of its items' strategy groups belong to,
## with Main winning ties. Module-path groups get a page the same way as role groups.
static func page_for_group(group: Dictionary, strategy: GenericStrategy) -> String:
	var votes := {"": 0}
	for item in group.items:
		var page := strategy.page_for_item(item)
		votes[page] = votes.get(page, 0) + 1
	var best := ""
	for page in votes:
		if votes[page] > votes[best]:
			best = page
	return best


## Group items by the first segment of their module path when the device's modules actually group
## parameters, otherwise by the sections their names spell out (`NameSections`, which also
## shortens labels: "Oscillator 1 Volume" → "Volume" in "Oscillator 1"), and whatever is left by
## the strategy (REQ-006). Groups are ordered by their most important item, then by first
## appearance, with the sections of one family ("Oscillator 1", "Oscillator 2") kept together;
## items keep their order inside a group.
static func group_items(items: Array[Dictionary], strategy: GenericStrategy) -> Array[Dictionary]:
	var use_modules := modules_group_parameters(items)
	var sections := {} if use_modules else NameSections.find(items)
	var by_id := {}
	var groups: Array[Dictionary] = []
	for item in items:
		var def: Dictionary
		var segment := module_segment(item.module)
		if use_modules and not segment.is_empty():
			def = {"id": "module_" + segment.to_lower().replace(" ", "_"), "title": segment}
		elif sections.has(item.index):
			def = sections[item.index]
			item.label = def.label
		else:
			def = strategy.group_for_item(item)
		var group: Dictionary = by_id.get(def.id, {})
		if group.is_empty():
			group = {"id": def.id, "title": def.title, "items": [], "importance": item.importance,
				"index": item.index, "family": def.get("family", def.id)}
			by_id[def.id] = group
			groups.append(group)
		group.items.append(item)
		group.importance = maxf(group.importance, item.importance)
	_share_family_rank(groups)
	groups.sort_custom(_by_importance)
	return groups


## Give every group of a family the family's best importance and first index, so the family sorts
## as one block; `family_order` keeps its groups in their own order inside it.
static func _share_family_rank(groups: Array[Dictionary]) -> void:
	var best := {}
	for group in groups:
		var rank: Dictionary = best.get(group.family, {})
		if rank.is_empty():
			best[group.family] = {"importance": group.importance, "index": group.index}
		else:
			rank.importance = maxf(rank.importance, group.importance)
			rank.index = mini(rank.index, group.index)
	for group in groups:
		group.family_order = group.index
		group.importance = best[group.family].importance
		group.index = best[group.family].index


## True when module paths carry grouping: some path is hierarchical ("Early/Size"), or two items
## share a first segment. Plugins with one flat module per parameter don't count.
static func modules_group_parameters(items: Array[Dictionary]) -> bool:
	var seen := {}
	for item in items:
		var module: String = item.module
		if module.is_empty():
			continue
		if module.contains("/"):
			return true
		if seen.has(module):
			return true
		seen[module] = true
	return false


## First segment of a module path ("Early/Size" → "Early").
static func module_segment(module: String) -> String:
	return module.get_slice("/", 0).strip_edges()


static func _by_importance(a: Dictionary, b: Dictionary) -> bool:
	if not is_equal_approx(a.importance, b.importance):
		return a.importance > b.importance
	if a.index != b.index:
		return a.index < b.index
	return a.family_order < b.family_order
