//! Ids for notes generated by note effects (spec 027 REQ-005).
//!
//! One engine-wide counter, so ids are unique across every note effect on every channel with
//! no allocator threaded through the device tree. Lock-free, so the audio thread and the
//! command thread can both draw from it.

use std::sync::atomic::{AtomicU32, Ordering};

use crate::audio::midi_types::{SoundingNoteId, GENERATED_ID_START, ID_RANGE_LEN};

#[allow(dead_code)] // Drawn by `NoteCx::emit_on`, used from wave 2 on.
static NEXT_GENERATED: AtomicU32 = AtomicU32::new(0);

/// A fresh generated id: in `[2^30, 2^30 + 2^29)` for a live origin, or in
/// `[2^30 + 2^29, 2^31)` when the note came from clip playback (`clip_origin`), so
/// `midi_types::is_clip_note` still tells them apart.
#[allow(dead_code)]
pub fn next_generated_id(clip_origin: bool) -> SoundingNoteId {
    let n = NEXT_GENERATED.fetch_add(1, Ordering::Relaxed) & (ID_RANGE_LEN - 1);
    let origin = if clip_origin { ID_RANGE_LEN } else { 0 };
    GENERATED_ID_START | origin | n
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::audio::midi_types::{is_clip_note, is_generated, ID_LIMIT};

    #[test]
    fn generated_ids_keep_origin_and_are_distinct() {
        let a = next_generated_id(false);
        let b = next_generated_id(false);
        let c = next_generated_id(true);
        assert_ne!(a, b);
        for id in [a, b, c] {
            assert!(is_generated(id) && id < ID_LIMIT);
        }
        assert!(!is_clip_note(a) && !is_clip_note(b) && is_clip_note(c));
    }
}
