#!/bin/bash
# Generate THIRD_PARTY_LICENSES at the repo root: the notices for everything a Sonara release
# bundles or links (Rust crates, sfizz's C++ libraries, Godot and its components, Godot addons).
# Run it before packaging a release and ship the file with the binaries.
#
# Needs: cargo-about (`cargo install cargo-about --locked --features cli`), godot 4.7 on PATH,
# and a built Engine (so the sfizz checkout exists).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/THIRD_PARTY_LICENSES"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

section() {
    printf '\n%s\n%s\n%s\n\n' "$(printf '=%.0s' {1..80})" "$1" "$(printf '=%.0s' {1..80})"
}

# Append one license file, headed by the component name.
notice() {
    printf '%s\n%s\n\n' "$(printf -- '-%.0s' {1..80})" "$1"
    cat "$2"
    printf '\n'
}

# Rust crates.
(cd "$ROOT/Engine" && cargo about generate --offline about.hbs -o "$TMP/rust.txt")

# sfizz's C++ sources and the libraries it links statically. The checkout lives next to the
# sfizz-sys crate that cargo resolved.
SFIZZ_SYS="$(cd "$ROOT/Engine" && cargo metadata --format-version 1 --offline \
    | python3 -c 'import json,sys; print(next(p["manifest_path"] for p in json.load(sys.stdin)["packages"] if p["name"] == "sfizz-sys"))')"
SFIZZ="$(dirname "$(dirname "$SFIZZ_SYS")")/vendor/sfizz"
[ -f "$SFIZZ/LICENSE" ] || { echo "sfizz sources not found at $SFIZZ" >&2; exit 1; }

# Godot engine and its bundled components.
godot --headless --path "$ROOT/Godot" -s ../scripts/godot_licenses.gd -- --test --out="$TMP/godot.txt" >/dev/null 2>&1
[ -s "$TMP/godot.txt" ] || { echo "Godot license export failed" >&2; exit 1; }

{
    echo "Third-party licenses for Sonara"
    echo
    echo "Sonara itself is licensed under the GNU General Public License v3.0 or later (see LICENSE)."
    echo "It includes or links the third-party software below, under the licenses shown."
    echo "Generated by scripts/gen_third_party_licenses.sh."

    section "Rust crates (Engine)"
    cat "$TMP/rust.txt"

    section "sfizz (C++ SFZ sampler, statically linked) and its bundled libraries"
    notice "sfizz" "$SFIZZ/LICENSE"
    for f in \
        external/abseil-cpp/LICENSE \
        external/atomic_queue/LICENSE \
        external/cephes/LICENSE.txt \
        external/filesystem/LICENSE \
        external/fmidi/LICENSE.md \
        external/invoke.hpp/LICENSE.md \
        external/jsl/LICENSE.md \
        external/simde/COPYING \
        external/st_audiofile/LICENSE.md \
        src/external/cpuid/LICENSE.rst \
        src/external/hiir/license.txt \
        src/external/kiss_fft/COPYING \
        src/external/pugixml/LICENSE.md \
        src/external/spline/LICENSE \
        src/external/tunings/LICENSE.md; do
        notice "sfizz: $(basename "$(dirname "$f")")" "$SFIZZ/$f"
    done

    section "libsndfile (dynamically linked system library)"
    echo "libsndfile is licensed under the GNU Lesser General Public License v2.1 or later."
    echo "Sonara links it dynamically; the system copy (or the bundled libsndfile.so) can be replaced."
    echo "Source: https://github.com/libsndfile/libsndfile"
    echo "License text: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt"

    section "Godot Engine (UI runtime)"
    cat "$TMP/godot.txt"

    section "Godot addons (Godot/addons/)"
    notice "GodOSC" "$ROOT/Godot/addons/godOSC/LICENSE"
    notice "Godot AI" "$ROOT/Godot/addons/godot_ai/LICENSE"
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
